export const back: string;
export const saving: string;
export const loading: string;
export const taskCheckbox: string;
export const taskDueDate: string;
export const taskTitle: string;
export const taskDescription: string;
export const taskTag: string;
export const removeTag: string;
